### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by ItsBean** [antonio-mastropaolo/LANCE#3]
Hello, dear authors:
In the models you provided, I only found the final model finetuned for log statement generation. Could you please provide the model that is only pretrained and have not been finetuned?

**Comment by antonio-mastropaolo** [comment]
Hi @ItsBean 

Unfortunately, we lost access to the stored checkpoint of the pre-trained models. 
Nonetheless, we recently submitted an extension of LANCE to a journal, which is currently under review.
Once accepted, we will disclose the replication package including the new pre-trained model, which I anticipate has been pre-trained on a dataset ~2 (twice) bigger than LANCE.

If you need LANCE's pre-trained model, then you can replicate the pre-training pipeline as it has been released in our replication package. In particular, the dataset is provided here https://drive.google.com/drive/folders/1D12y-CIJTYLxMeSmGQjxEXjTEzQImgaH while the code is accessible at the following link: https://github.com/antonio-mastropaolo/LANCE/blob/main/Code/Pre-training/Pre_training.ipynb
